# Generated by Django 6.0.2 on 2026-05-11 14:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('streak_100', '100-Day Streak'), ('habits_5', '5 Habits Created'), ('habits_10', '10 Habits Created'), ('completions_50', '50 Completions'), ('completions_100', '100 Completions'), ('perfect_week', 'Perfect Week'), ('perfect_month', 'Perfect Month'), ('level_5', 'Reached Level 5'), ('level_10', 'Reached Level 10'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#6c5ce7', 'Purple'), ('#00b894', 'Green'), ('#fd79a8', 'Pink'), ('#fdcb6e', 'Yellow'), ('#0984e3', 'Blue'), ('#e17055', 'Orange'), ('#a29bfe', 'Lavender'), ('#55efc4', 'Mint')], default='#6c5ce7', max_length=10)),
                ('icon', models.CharField(choices=[('bi-heart-pulse', 'Health'), ('bi-book', 'Learning'), ('bi-lightning', 'Fitness'), ('bi-piggy-bank', 'Finance'), ('bi-emoji-smile', 'Mindfulness'), ('bi-people', 'Social'), ('bi-briefcase', 'Work'), ('bi-stars', 'Personal')], default='bi-stars', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays Only'), ('weekends', 'Weekends Only')], default='daily', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('target_days', models.IntegerField(default=30, help_text='Target number of days to complete')),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(default='#6c5ce7', max_length=10)),
                ('icon', models.CharField(default='bi-check-circle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('xp_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('total_habits_completed', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('mood', models.IntegerField(default=3, help_text='1-5 mood rating')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
