# Generated by Django 4.2.30 on 2026-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_embed_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
