# Generated by Django 4.2.30 on 2026-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile_spotify_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='streak_frozen',
            field=models.BooleanField(default=False, help_text='Day preserved by a streak freeze'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_freezes',
            field=models.IntegerField(default=3, help_text='Streak freeze tokens available'),
        ),
    ]
